# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: booksetl
services:
  postgresql:
    environment:
      POSTGRES_DB: booksEtl
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: booksEtl
    image: postgres:17.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres-data:
