# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: booksetl
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  tesseract:
    extends:
      file: ./tesseract.yml
      service: tesseract
