# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: booksetl
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  tesseract:
    extends:
      file: ./tesseract.yml
      service: tesseract
  postgresql-temporal:
    extends:
      file: ./temporal.yml
      service: postgresql-temporal
  temporal:
    extends:
      file: ./temporal.yml
      service: temporal
  temporal-admin-tools:
    extends:
      file: ./temporal.yml
      service: temporal-admin-tools
  temporal-ui:
    extends:
      file: ./temporal.yml
      service: temporal-ui

volumes:
  postgres-data:
  temporal-postgres-data:
