services:
  postgresql:
    environment:
      POSTGRES_USER: booksEtl
      POSTGRES_DB: booksEtl
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:17.4
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/temporal/:/var/lib/postgresql/data/temporal
  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=booksEtl
      - POSTGRES_PWD=
      - POSTGRES_SEEDS=postgresql
      - DBNAME=booksEtl
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:1.25.0
    ports:
      - 7233:7233
  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.25
    stdin_open: true
    tty: true
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.26.2
    ports:
      - 8282:8080

volumes:
  temporal-postgres-data:
